#!/bin/sh

for d in $XMONAD_CONFIG_DIR $XDG_CONFIG_HOME "$HOME"/.xmonad
  if test -d $d
    set xmonad_dir $d
    break
  end
end

if test -z "$xmonad_dir"
  test -n "$HOME" || exit 1
  test -d "$HOME"/.xmonad || exit 2
  set xmonad_dir "$HOME"/.xmonad 
end


mkdir -p "$xmonad_dir"/lib/

echo "copying to $xmonad_dir/lib/"
echo

for d in typeclasses dummy notify-send hslibnotify; do
  cp -vR "$d"/src/* "$xmonad_dir"/lib/
done

